name: Add a new book
on:
  issues:
    types: [opened, edited]
jobs:
  add-book:
    if: ${{ github.event.issue.title == '本追加' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update books.json
        run: |
          echo "${{ github.event.issue.body }}" | while read isbn; do
            bash add_book.bash $isbn
          done
      - name: Commit a change
        run: |
          git config user.name 'jinpei0908'
          git config user.email 'jinpei0908@gmail.com'
          git commit -am '本追加'
      - name: Create Pull Request if `本追加` in issue title
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Add books and close #${{ github.event.issue.number }}"
