name: Add a new book
on:
  issues:
    types: [opened, edited]
jobs:
  check-bats-version-and-echo-issue-body:
    if: contain( ${{ github.event.issue.title }}, '本追加')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write issue body in foo.txt
        run: echo "Issue body ${{ github.event.issue.body }}" > foo.txt
      - name: Create Pull Request if `本追加` in issue title
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Add books and close #${{ github.event.issue.number }}"
